safe:        false
port: 4000
baseurl:     /
url:         http://localhost:4000
source:      .
destination: ./_site
plugins_dir:     ./_plugins
future:      true
markdown:    kramdown
permalink:   date